### ISSUE TITLE
1장 사용자 수에 따른 규모 확장성 - 메시지 큐

### ISSUE THREAD

**Issue by ilpyoyang** [BacknPacker/large_scale_system_design#2]
**큐의 크기가 커지면 더 많은 작업 프로세스를 추가해야 처리 시간을 줄일 수 있습니다. 하지만 큐가 거의 항상 비어있는 상태라면 작업 프로세스의 수는 줄일 수 있을 것입니다.**

When the size of the queue becomes large, more workers are added to reduce the processing time. However, if the queue is empty most of the time, the number of workers can be reduced.

이 부분의 말이 약간 어색해서 원어 버전을 찾아봤습니다.  

생산자와 소비자는 독립적 확장이 가능한데 큐의 크기가 커지면 더 많은 생산자를 추가할 수 있습니다.  거의 항상 비어 있는 상태라면 작업자의 수를 줄일 수 있습니다.  

이렇게 되어 있어서 한글판 혼동이 있을 것 같아 이슈 남깁니다 👍 
참고로 저는 ebook 버전인데 다른 분들은 알려주세요!

**Comment by Kimsihwan** [comment]
작업자의 수가 생산자랑 같은 의미인거죠?

**Comment by ilpyoyang** [comment]
넵넵 해석본에 오타가 있었네요 수정해놨습니다!

**Comment by Ilpyo-Yang** [comment]
> 작업자의 수가 생산자랑 같은 의미인거죠?

넵넵 해석본에 오타가 있었네요 수정해놨습니다!
