### ISSUE TITLE
3주차 6장. p98 데이터 다중화 질문

### ISSUE THREAD

**Issue by ilpyoyang** [BacknPacker/large_scale_system_design#7]
p98.
**그런데 가상 노드를 사용한다면 위와 같이 선택한 N개의 노드가 대응될 실제 물리 서버의 개수가 N보다 작아질 수 있다.**

이 부분이 N개 가상노드를 선택했는데 실제로는 같은 서버의 가상노드들이 섞여 있어 대응될 실제 물리 서버 수가 N보다 작아질 수 있는다는 말이 맞나요??

**Comment by Kimsihwan** [comment]
아마 제 생각에는 가상 노드 서버를 사용하면 같은 물리 서버를 사용하고있는 가상 노드 서버가 겹쳐서 그럴꺼같다고 생각해요!
