### ISSUE TITLE
3주차 6장. p116 버전 충돌 확인 방법

### ISSUE THREAD

**Issue by Kimsihwan** [BacknPacker/large_scale_system_design#8]
버전 충돌 확인 방법이 약간 이해가 안가는 부분이 있습니다.

버전 충돌 기준이 Y의 벡터 시계 구성요소 중 X의 벡터 시계 동일 서버 기준으로 구성요소 보다 작은 값이 있는지 확인 하면된다고 하는데
예시는
X 벡터 시계 D([s0, 1], [s1, 2])
Y 벡터 시계 D([s0, 2], [s1, 1])일 경우

S1 서버 기준으로 X 벡터 시계 보다 2 > 1이닌깐 충돌이 일어 났다고 볼수있는데

![추상로직](https://github.com/BacknPacker/large_scale_system_design/assets/37168993/39a08a8f-9ec3-4d71-9690-697dc4fc78a4)

위에 추상적 로직에 적용하려면 어떻게 적용해서 봐야할지 모르겠습니다.

**Comment by ilpyoyang** [comment]
추상적 로직에 적용해서 봐야한다는 부분에서 제가 이해를 못했어요!
D3과 D4에서 보면 벡터시계의 Sx 기준으로 둘 다 2의 값을 가지고 있지만 각각 Sy, Sz의 다른 정보를 가지고 있어서 충돌이 났다고 보면 될 것 같아요!

써주신 예시에서  D([s0, 1], [s1, 2])와 D([s0, 2], [s1, 1])가 있다면, 
s0의 시간적 흐름이 0 -> 2가 되는데, 
s1의 시간적 흐름이 2 -> 1이 되기는 어려울 것 같아요!

제가 이해를 못한 것일 수도 있어서 이따가 스터디에서 논의하고 다시 적어볼게요!
